### ISSUE TITLE
Okta Authentication / How to authenticate when IDP metadata is external

### ISSUE THREAD

**Issue by syntacticsolutions** [tngan/samlify#164]
Hi, I was looking through your documentation and I noticed that the idp metadata is required to parse the SAML response. My IDP is external and I'm not sure how to provide the information that is needed to make the framework work properly.  With passport I just pass the EntityID, SAML path, entrypoint, and x.509 cert to the framework and it knows how to handle it.

I was also looking through your documentation and it shows "In Progress" for the Okta Auth Example. I was wondering if maybe this is something that I can help with to get the ball rolling since I need it to work with Okta Anyways.

**Comment by tngan** [comment]
@syntacticsolutions 

In common practice, IdP would provide metadata for you to integrate to your current application like Okta and OneLogin. Does your external IDP provide you a metadata ? Otherwise, I think you can make one. In fact, we don't need user to import metadata but construct the entity instance by simply passing in minimal required information, e.g. EntityID, entrypoint, cert. I think we didn't remove that piece but just not documented it nicely. 

For the Okta implementation, I have tested which works properly few months ago. My current daily workload is heavy, so feel free to make a pull request, I am happy to accept it as well.

**Comment by syntacticsolutions** [comment]
I ended up figuring it out. I was getting a SAML assertion from my IDP that
was encoded in base64. All I needed was to decode it and parse the xml out
to get the attributes I wanted. I don't think it's the same scenario here.

You can close this ticket for now :)

Thank you!

**Comment by emhagman** [comment]
@syntacticsolutions Thanks, your comment allowed me to figure this out as well. I believe what you were referring to is for IDP-initiated login, we need the **entityId** to determine which IDP to create using samlify
