### ISSUE TITLE
Invalid X509 Serial Number Problem

### ISSUE THREAD

**Issue by rastko-florencehc** [tngan/samlify#198]
When having a SAML response with xml that contains:
```
<ds:X509SerialNumber>20630951819271670505357133780297999999</ds:X509SerialNumber>
```

calling:
```
serviceProvider.parseLoginResponse
```

raises following error:
```
this is not a valid saml response with errors: Error: Element '{http://www.w3.org/2000/09/xmldsig#}X509SerialNumber': '20630951819271670505357133780297488388' is not a valid value of the atomic type 'xs:integer'.
```

Any ideas how can I fix this?

**Comment by tngan** [comment]
@rastko-florencehc Which version of samlify are you using ?

**Comment by rastko-florencehc** [comment]
It's 2.3.3

**Comment by tngan** [comment]
@rastko-florencehc Can you try the serial number with length less than 24 digits ? There is a [bug report](https://mail.gnome.org/archives/xml/2008-March/msg00051.html) for this.

**Comment by rastko-florencehc** [comment]
@tngan Yes, we have some other cases where serial number is less than 24 digits and it works. Can you recommend any solution for this?

**Comment by tngan** [comment]
@rastko-florencehc Since some CAs use large number to prevent sequence guessing, but not all xml libraries are able to handle this big integer (at least not the one 2.3.3 is using). [Ref: Section 2.6.2](http://docs.oasis-open.org/security/saml/Post2.0/sstc-saml2-holder-of-key-cs-02.pdf)

And the workaround (I haven't tried it but you can definitely give it a try) is to define the schema for `ds:X509SerialNumber` from `integer` to `string`.

https://github.com/tngan/samlify/blob/56480f7852baba147389403cc5f3fe826c0f2e39/schemas/xmldsig-core-schema.xsd#L200

**Comment by rastko-florencehc** [comment]
@tngan thank you! I'll give it a try.

**Comment by tngan** [comment]
@rastko-florencehc Feel free to let me know if you resolve this issue.

**Comment by rastko-florencehc** [comment]
@tngan Would you consider this change if I make a PR with this update?

**Comment by rastko-florencehc** [comment]
@tngan I understand that... It's a bit of a limbo place between RFC document and libxml2 bad implementation. This will brake for anyone 'lucky' enough to have X509 serial number long enough.

**Comment by tngan** [comment]
@rastko-florencehc After I reviewed some other 3rd party libraries, they have changed to use string in order to get rid of libxml2 limitation. It's also easy to make this change here rather than changing the implementation of CA.

So, feel free to make a PR.

**Comment by tngan** [comment]
@rastko-florencehc Thank you so much for suggesting this issue, this will be released in rc3.

**Comment by rastko-florencehc** [comment]
@tngan no problem! Thank you for accepting it!
