### ISSUE TITLE
Pluggable xml validation

### ISSUE THREAD

**Issue by tngan** [tngan/samlify#228]
We would like to provide three validation methods.

- Delegate to java runtime library
- Delegate to libxmljs-mt 
- No validation (will enable only in DEV mode)

**Comment by tngan** [comment]
POC: 43d84d0b0a4fb6f544160e2bf5f9aa0cb1733917

**Comment by maybeec** [comment]
One question regarding this. I have seen that at installation time you have to set the env var `SAML_VALIDATOR`. Is this saved in the package.json as well? Otherwise, how can I assure best, that everybody in the team or any build on the CI is utilizing the correct validation mechanism?

On clean npm install it would simply disable validation if the variables was not set.
By "DEV mode" do you refer to the angular dev/prod mode?

**Comment by tngan** [comment]
Hi, @maybeec 

You can just add a pre-install npm script in the package.json in your project.

```
"preinstall": "export SAML_VALIDATOR=libxml"
```
