### ISSUE TITLE
Question: Integrating SAML with JWT mechanism

### ISSUE THREAD

**Issue by dakshshah96** [tngan/samlify#250]
Hi, thanks for making this library! 🙏 
Please let me know if this is not the right place to ask this question.

I have a Node.js GraphQL server built using apollo-server running in production for the past one year. Authorization is handled by means of the graphql-shield library and JWT tokens in the request Authorization header.

Now, we have a new enterprise client and they want to log in via SAML using their server as IdP and obviously, ours will be the SP.

How can I send back a JWT token to the client once the SAML authentication is successfully completed? What is the right way to do handle this sort of a situation so I don't have to re-architecture how we handle authorization throughout our server and continue using JWT?

**Comment by tngan** [comment]
@dakshshah96 Thanks for your support firstly. SAML is a protocol doing authentication and authorization. Instead of the re-architecture, what you can do is to sign the JWT after SAML response is validated and parsed.

The payload inside JWT can be taken out from the SAML response issued by the IdP. In other words, the authorization process can be leveraged to the IdP and that's what IdP supposes to do.

The workflow is like, to keep it simple, let me use IdP-initiated single sign on as an example.

1. User access the single sign on endpoint in IdP for your service
2. IdP asks for credential to login IdP
3. IdP does the authentication and authorization, sending back SAML response to your SP access consumer URL (the endpoint where your SP accepts the response)
4. Sign JWT with payload taken from the SAML response (i.e. role info, email, password ... etc)

**Comment by dakshshah96** [comment]
@tngan Thank you so much for the quick answer! That makes it much more clearer.
