### ISSUE TITLE
Clock Drift and NotBefore

### ISSUE THREAD

**Issue by sandmman** [tngan/samlify#256]
We are frequently seeing SAML response validation errors when the SP clock becomes out of sync with the IdP. Many other libraries have exposed some sort of `acceptedClockSkew` field in order to handle this case.

Are there any plans to update the library to handle clock skew (it should be a fairly small change) / are there any ways to disable validation, so we can perform it manually?

Example: 
- [notBefore_skew in saml2-js](https://www.npmjs.com/package/saml2-js)

See similar issues:
- https://github.com/onelogin/ruby-saml/issues/17

**Comment by tngan** [comment]
Hi @sandmman, how long is the clock skew in your case.

**Comment by sandmman** [comment]
@tngan It's not particularly long (less than a second in my case), but in our situation we are acting as a SP for SAML identity providers configured by our users.

Meaning, our system has to work with *any* SAML IdP that we are linked to by our users. Generally, we'll have no control over syncing clocks, so we'd like to be able to expose that same parameter to our own users for them to configure as they like.

**Comment by tngan** [comment]
@sandmman This is valid. You can expect there will be a new parameter that can passed into the constructor of service provider once this issue is implemented.

```js
const sp = serviceProvider({
  ...
  notBeforeSkewed: true
});
```

Default value would be `false`.

**Comment by sandmman** [comment]
I really appreciate the quick response thanks!

**Comment by keerthivasan-r** [comment]
@tngan @sandmman How much clock skew for should be right in this case?  How do we approach this problem? It will be just for 'notBefore', what about 'notAfter'?

**Comment by tngan** [comment]
@keerthivasan-r Usually the expiration time for saml response is around 5 minutes to 10 minutes, the clock skew for notAfter is actually useless in this case, because the `notBefore` check is relatively close to the issued time of response.

UPDATE: this feature will be implemented and included in the next patch release

`notBeforeSkew` would be a number instead of a boolean

**Comment by fas3r** [comment]
Hello @tngan , 

Im sorry to ask here but as it's related I can open a new issue if you want. 

I dont know if you remember but I wrote the okta article and at that time I was still using the 2.5 and I  just migrated to 2.7.1. 

However now I'm getting the warning `You intend to have time validation however the document doesn't include the valid range`

I checked in the okta application and I dont see how to set `NotBefore` and `notAfter`.  Is it something that I need to create on my own with  the [template & attribute](https://samlify.js.org/#/template) ?  

Thanks

**Comment by PrasanthVijayy** [comment]
Hi @tngan!

Since I added the clockDrift to overcome the clockSkew error!

` clockDrifts: [-2000, 2000]`

But unfortunately I still see the not applied for the `NotBefore` correctly. Is there any ways to overcome this issue?
`Also tried adding notBeforeSkewed: true` but not resolved.

With the similar issues opened previously has not given clear idea (for me). 

**Can you suggest to overcome this issue which is highly appreciable!**
