### ISSUE TITLE
Dynamically creating Identity providers

### ISSUE THREAD

**Issue by ugolas** [tngan/samlify#83]
Hi,

We are implementing a sso feature in our system, which will allow our clients to configure their own identity providers (each client might use a different one), and login using them.

This requires identifying the relevant idp for every saml request and instantiating a new IdentityProvider instance for every saml request.

Two challenges we've encountered so far which I would like to get help for:
1. We save the idp metadata in the DB per client, and extract them depending on the relevant client, I noticed the IdentityProvider constructor accepts the 'signingCertFile' field as a path to a local file, is there a way to just pass the string of the cert instead? Is it worth creating a pull requests with this feature?

2. I saw the code that parses the cert (parseCerFile) uses 'fs.readFileSync' - which should not be used as part of handling requests in the service - so even if we save all certs in files won't be a good idea to load them dynamically.

Finally, I saw discussions about v2.0 - how far are you from it? 

Appreciate any help guys!

**Comment by tngan** [comment]
For the two abovementioned questions, we allow user to pass in string (e.g. the string obtained from database, the string read from files) in both metadata, certificate and key files. Credits to @sebakerckhof.

v2 itself will be released by the end of this week.

**Comment by ugolas** [comment]
Thanks for the reply!

Is this supported in version 1.4.1? (the version I'm currently integrating with)

In the code I saw that only passing a path to a file is supported:
`        
        if(signingCertFile) {
            IDPSSODescriptor.push(SamlLib.createKeySection('signing', signingCertFile));
        } else {
            console.warn('Construct identity provider - missing signing certificate');
        }
`

**Comment by tngan** [comment]
Unfortunately, v1.4.1 only support the path to file. For v2, the rc.1 was released yesterday.

You can install it using `npm install samlify@2.0.0-rc.1`. Since we are still working on the documentation and test cases, you can checkout the test files to see how to construct the identity provider during the meantime.

**Comment by tngan** [comment]
@ugolas This issue isn't updated for a while, so I close it first. Feel free to reopen it if needed.

**Comment by ugolas** [comment]
HI,

I'm trying to integrate the '2.0.0-rc.2' and U just want to make sure a few things, will re-use this issue for questions:

1. Does the library validates the following: audience, recipient, statusCode? I'm trying to test it and when I change these values the parseLoginResponse is still successful. Do I need to implement these validations manually or am I not using the lib correctly?

2. I can't seem to manage to fail the signature validation, I've tried changing the signatureValue but still its succeeds.

Appreciate the assistance!

PS.
Do you have an estimation for final release of v2.0? This lib is a life saviour :)

**Comment by tngan** [comment]
Hi @ugolas,

1. The validation is left to users, this library only does the basic and important checking (e.g. signature validation and decryption), but you can get back those attributes from the extract object.

See the test case [here](https://github.com/tngan/samlify/blob/master/test/flow.ts#L392), this case could be the most complicated response, with customize template including attributes, message signature and encrypted signed assertion as well.

2. It would be good if you can make a sample repository, or give more detail that how you construct the idp and sp.

There will be v2.0.0-rc.3 within this week, probably today, this release includes the test coverage on single logout service and some bug fixes and refactor. Then final release will be done next week since it could have been well tested.

**Comment by tngan** [comment]
For 2, I think I might know what happened, thanks for catching it.

**Comment by tngan** [comment]
@ugolas Please try again with v2.0.0-rc.3.

**Comment by ugolas** [comment]
thanks for the quick reply!

I get invalid for installing  v2.0.1-rc.3 , but I tried v2.0.0-rc.3, and now the signature validation fails pretty much for every change I make to the XML - thats great!

**Comment by tngan** [comment]
@ugolas Just do `npm install samlify@2.0.1-rc.3`, the v2.0.0-rc.3 only checks the first signature found. I will add more message integrity tests before the release in early next week.

**Comment by tngan** [comment]
@ugolas v2.0.0 is released officially today.
